spring:
  application:
    name: springboot-task-api

  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

server:
  port: ${PORT:5000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.web: DEBUG   # Show handler + "Completed 200 OK" lines
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.yourcompany.todo: DEBUG      # Your code logs

  mvc:
    log-request-details: true        # Allow Spring to include potentially sensitive request details at DEBUG level

# === PROD LATER ===
# logging:
#   level:
#     org.springframework.web: INFO
#     org.springframework.web.servlet.DispatcherServlet: INFO
#     com.yourcompany.todo: INFO
#
# spring:
#   mvc:
#     log-request-details: false
